### ISSUE TITLE
P-2812HNU-F1

### ISSUE THREAD

**Issue by cmhrky** [PlumLulz/p2812py#1]
![p-2812hnu-f1](https://github.com/PlumLulz/p2812py/assets/17867666/f9180848-99b7-4e31-a751-65d198d10a8a)

**Comment by drsn00ker** [comment]
Excellent find! Never seen a non-Telenor P-2812HNU before. The keygen is only for the Telenor ISP. 
Luckily, this ZyXEL model is covered by zykgen using the screw driver cocktail!

**Comment by PlumLulz** [comment]
> Excellent find! Never seen a non-Telenor P-2812HNU before. The keygen is only for the Telenor ISP. Luckily, this ZyXEL model is covered by zykgen using the screw driver cocktail!

Thanks for clearing that up.
